const productos = [
    {
    'id':01,
    'img':'https://www.honda.mx/web/img/motorcycles/models/naked/cb650r/gallery/1.jpg',
    'marca':'HONDA',
    'name':'CB650R',
    'fecha de produccion':2022,
    'categoria':'NAKED',
    'precio':'$203,000',
    'valor':203000,
    'descripcion':'La nueva CB650R con su característico rendimiento deportivo y un diseño estilizado y aerodinámico, está listo para la aventura.',
    'oferta':false
    },{
    'id':02,
    'img':'https://www.honda.mx/web/img/motorcycles/models/supersport/cbr1000rr/gallery/1.jpg',
    'marca':'HONDA',
    'name':'CBR1000RR',
    'fecha de produccion':2023,
    'categoria':'SUPER SPORT',
    'precio':'$332,000',
    'valor':332000,
    'descripcion':'duro',
    'oferta':true,
    },{
    'id':03,
    'img':'https://www.honda.mx/web/img/motorcycles/models/navi/navi/colors/blanco.png',
    'marca':'HONDA',
    'name':'NAVI 110',
    'fecha de produccion':2023,
    'categoria':'NAVI',
    'precio':'$30,490',
    'valor':30490,
    'descripcion':'Se utiliza la plataforma de un scooter para el diseño de este vehículo pero se combina con las características de una motocicleta, lo que lo convierte en un vehículo Crossover, es decir es el resultado de la mezcla de lo mejor de ambos segmentos.',
    'oferta':true,
    },{
    'id':04,
    'img':'https://ic1.maxabout.us/autos/tw_india//N/2020/9/new-kawasaki-z900-candy-lime-green.jpg',
    'marca':'KAWASAKI',
    'name':'Z900 SE',
    'fecha de produccion':2023,
    'categoria':'SUPER SPORT',
    'precio':'$284,000',
    'valor':284000,
    'descripcion':'Incorpora una gran cantidad de características nuevas y avanzadas, y personifica la creencia de Kawasaki de lo que debería ser una motocicleta sin carenado ideal. Con 948 cc y un chasis ultraligero, cada viaje aporta una potencia, capacidad de respuesta y emoción excepcionales. El estilo distintivo inspirado en Sugomi evoluciona, dando lugar a una imagen audaz y agresiva que seguramente atraerá la atención.',
    'oferta':false, 
    },{
    'id':05,
    'img':'https://storage.kawasaki.eu/public/kawasaki.eu/en-EU/model/20ZX636G_201GN2DRS3CG_A.001.png',
    'marca':'KAWASAKI',
    'name':'NINJA ZX6R',
    'fecha de produccion':2023,
    'categoria':'SUPER SPORT',
    'precio':'$244,900',
    'valor':244900,
    'descripcion':'La Ninja ZX6R deportiva, legendario rendimiento de la moto deportiva para experimentar el nivel supremo de actitud y confianza que solo la Ninja puede ofrecer. ',
    'oferta':false,
    },{
    'id':06,
    'img':'https://cdn.shopify.com/s/files/1/0420/4258/9349/products/ninja-h2_2023_1024x1024@2x.jpg?v=1667434896',
    'marca':'KAWASAKI',
    'name':'NINJA H2',
    'fecha de produccion':2023,
    'categoria':'HYPER SPORT',
    'precio':'$850,000',
    'valor':850000,
    'descripcion':'La Ninja H2 de Kawasaki lleva a las calles la potencia alucinante de las hiperdeportivas sobrealimentadas para carreras de Kawasaki. Con un potente motor de cuatro cilindros en línea de 998 cc, electrónica de última generación y los últimos frenos Brembo, el resultado final es puro rendimiento en carretera.',
    'oferta':true,
    },{
    'id':07,
    'img':'https://www.yamaha-motor.com.mx/images/motos/mt03abs23_3.jpg',
    'marca':'YAMAHA',
    'name':'MT-03 ABS',
    'fecha de produccion':2023,
    'categoria':'NAKED',
    'precio':'$154,000',
    'valor':154000,
    'descripcion':'La nueva MT-03 llega al mercado mexicano con una propuesta agresiva e intimidante.Con un desempeño excepcional y diseño impactante, la nueva MT-03, ahora con ABS vuelve a elevar el concepto de las motocicletas Naked de mediana cilindrada en México.',
    'oferta':false,
    },{
    'id':08,
    'img':'https://www.yamaha-motor.com.mx/images/motos/mt09_22_2.jpg',
    'marca':'YAMAHA',
    'name':'MT-09',
    'fecha de produccion':2022,
    'categoria':'NAKED',
    'precio':'$299,000',
    'valor':299000,
    'descripcion':'Su motor CP3 de 890 cc de gran capacidad que genera más potencia con menos revoluciones, brinda una aceleración de mejor respuesta y unas mejores prestaciones en la carretera.Una IMU de 6 ejes de alta tecnología que regula las mejores prestaciones electrónicas para el conductor y otorgarle el máximo control de manejo.',
    'oferta':false,
    },{
    'id':09,
    'img':'http://motos-b60.kxcdn.com/sites/default/files/yamaha-yzf-r1-2020.jpg',
    'marca':'YAMAHA',
    'name':'YZF-R1',
    'fecha de produccion':2022,
    'categoria':'SUPER SPORT',
    'precio':'$499,000',
    'valor':499000,
    'descripcion':'Ya desde sus inicios, la YZF-R1 se ha fabricado sin renunciar a nada, y es precisamente esta filosofía de diseño lo que convierte a esta Yamaha en la moto superdeportiva más emocionante de nuestro tiempo.',
    'oferta':true,
    },{
    'id':10,
    'img':'https://azwecdnepstoragewebsiteuploads.azureedge.net/PHO_BIKE_90_RE_RC390-BLUE-MY22-90-Right-MY23-Studio_%23SALL_%23AEPI_%23V1.png',
    'marca':'KTM',
    'name':'KTM RC 390',
    'fecha de produccion':2023,
    'categoria':'SPORT',
    'precio':'$131,900',
    'valor':131900,
    'descripcion':'La KTM RC 390 2023 es una máquina superdeportiva de alto rendimiento, con unas sólidas raíces de moto de circuito. Con un impresionante paquete tecnológico de componentes, así como un estilo derivado de la competición, unas características de comportamiento y una adictiva entrega de potencia, la KTM RC 390 es una moto de competición para el mundo real dotada de un indudable pedigrí. ',
    'oferta':true,
    },{
    'id':11,
    'img':'https://azwecdnepstoragewebsiteuploads.azureedge.net/PHO_BIKE_90_RE_1290-sdr-22-wh-90re_%23SALL_%23AEPI_%23V1.png',
    'marca':'KTM',
    'name':'KTM 1290 SUPER DUKE R',
    'fecha de produccion':2023,
    'categoria':'NAKED',
    'precio':'$389,900',
    'valor':389900,
    'descripcion':'Asentada en lo más alto del reino del segmento hypernaked y con una intimidante colección de especificaciones de chasis y motor de altas prestaciones, así como con sistemas de asistencia al pilotaje y una electrónica de alto nivel, la KTM 1290 SUPER DUKE R no necesita de presentación. Pero se la haremos de todos modos. Presentamos a THE BEAST.',
    'oferta':true,
    },{
    'id':12,
    'img':'https://suzuki-motos.s3.amazonaws.com/assets/prod-publish/7592/azul-moto-gp.png',
    'marca':'SUSUKI',
    'name':'GSX-R150',
    'fecha de produccion':2022,
    'categoria':'SPORT',
    'precio':'$83,690',
    'valor':83690,
    'descripcion':'Quién dice que el alma deportiva la llevan solo quienes ruedan en la pista o aquellos con motos de mayor cilindrada? ¡Para nada! Con GSX-R150 tú también eres parte de esta élite. Es tu momento de salir a las calles todos los días luciendo totalmente sport y con la mejor tecnología deportiva, directo de la serie GSX-R.',
    'oferta':false,
    },{
    'id':13,
    'img':'https://suzuki-motos.s3.amazonaws.com/assets/prod-publish/8854/gris.png',
    'marca':'SUSUKI',
    'name':'GSXR1000A',
    'fecha de produccion':2022,
    'categoria':'SPORT',
    'precio':'$345,990',
    'valor':345990,
    'descripcion':'Calidad inigualable sin rival que le ha permitido posicionarse como el “Rey de las motos deportivas” y una de las favoritas en su clase. Con GSX-R1000A no solo obtienes el mejor desempeño: vives la adrenalina al filo de emociones extremas.',
    'oferta':true,
    },{
    'id':14,
    'img':'https://images.ctfassets.net/x7j9qwvpvr5s/3MSkaTbWAooqyi8Sk68YSW/553db4954cf9cd763cacaee4e98e365b/Supersport-MY18-Grey-02-Slider-Gallery-1920x1080.jpg',
    'marca':'DUCATI',
    'name':'SUPER SPORT 950',
    'fecha de produccion':2022,
    'categoria':'SUPER SPORT',
    'precio':'309,800$',
    'valor':309800,
    'descripcion':'La moto deportiva de Ducati hecha para la carretera cambia de nombre y se convierte en SuperSport 950, renovando su estética, equipamiento electrónico y alto nivel de prestaciones. ',
    'oferta':false,
    },{
    'id':15,
    'img':'https://mediapool.bmwgroup.com/cache/P9/201810/P90328653/P90328653-bmw-r-1250-rs-exclusive-11-2018-600px.jpg',
    'marca':'BMW',
    'name':'R 1250 RS',
    'fecha de produccion':2023,
    'categoria':'SPORT',
    'precio':'$405,200',
    'valor':405200,
    'descripcion':'Cada viaje está determinado por dos factores: el tiempo y el recorrido. Con la nueva BMW R 1250 RS sacas más recorrido de cada viaje. El potente par motor de 143 Nm y los 100 kW (136 CV) del nuevo motor boxer te acelerarán aún más rápido a tu velocidad de crucero.',
    'oferta':false,
    }
]